# 导入其他配置文件
spring:
  config:
    import:
      - classpath:config/application-server.yml
      - classpath:config/application-datasource.yml
      - classpath:config/application-jwt.yml
      - classpath:config/application-security.yml
      - classpath:config/application-app.yml
      - classpath:config/application-logging.yml
      - classpath:config/application-redis.yml
